// this file is used to store JSON

package teltonikajson

// FM36 holds JSON representation of AVL IO elements for devices family FM36
const FM36 string = `{
	"1":{
	   "No":"1",
	   "PropertyName":"Digital Input Status 1",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"Logic: 0 / 1",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint8"
	},
	"2":{
	   "No":"2",
	   "PropertyName":"Digital Input Status 2",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"Logic: 0 / 1",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint8"
	},
	"3":{
	   "No":"3",
	   "PropertyName":"Digital Input Status 3",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"Logic: 0 / 1",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint8"
	},
	"4":{
	   "No":"4",
	   "PropertyName":"Digital Input Status 4",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"Logic: 0 / 1",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint8"
	},
	"9":{
	   "No":"5",
	   "PropertyName":"Analog Input 1",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"30000",
	   "Multiplier":"-",
	   "Units":"mV",
	   "Description":"Voltage: mV, 0 – 30000 mV",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint16"
	},
	"10":{
	   "No":"6",
	   "PropertyName":"Analog Input 2",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"30000",
	   "Multiplier":"-",
	   "Units":"mV",
	   "Description":"Voltage: mV, 0 – 30000 mV",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint16"
	},
	"21":{
	   "No":"7",
	   "PropertyName":"GSM level",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"1",
	   "Max":"5",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"GSM signal level value in scale 1 – 5",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint8"
	},
	"24":{
	   "No":"8",
	   "PropertyName":"Speed",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1000",
	   "Multiplier":"-",
	   "Units":"km/h",
	   "Description":"Value in km/h, 0 – xxx km/h",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint16"
	},
	"66":{
	   "No":"9",
	   "PropertyName":"External Power Voltage",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"30000",
	   "Multiplier":"-",
	   "Units":"mV",
	   "Description":"Voltage: mV, 0 – 30000 mV",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint16"
	},
	"67":{
	   "No":"10",
	   "PropertyName":"Battery Voltage",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"30000",
	   "Multiplier":"-",
	   "Units":"mV",
	   "Description":"Voltage: mV, 0 – 30000 mV",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint16"
	},
	"68":{
	   "No":"11",
	   "PropertyName":"Battery Current",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"2400",
	   "Multiplier":"-",
	   "Units":"mA",
	   "Description":"Current: mA, 0 – 2400 mA",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint16"
	},
	"69":{
	   "No":"12",
	   "PropertyName":"GNSS Status",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"10",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"States:0 – GPS module is power off.1 – GPS antenna is disconnected.2 – Working, no GPS FIX.3 – Working, GPS FIX acquired.4 – GPS sleep.5 – GPS antenna is short circuited.",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint8"
	},
	"72":{
	   "No":"13",
	   "PropertyName":"Dallas Temperature 1",
	   "Bytes":"2",
	   "Type":"Signed",
	   "Min":"-55",
	   "Max":"3000",
	   "Multiplier":"10",
	   "Units":"°C",
	   "Description":"10 * Degrees ( °C ), -55 - +115, if 3000 – Dallas error",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toInt16"
	},
	"73":{
	   "No":"14",
	   "PropertyName":"Dallas Temperature 2",
	   "Bytes":"2",
	   "Type":"Signed",
	   "Min":"-55",
	   "Max":"3000",
	   "Multiplier":"10",
	   "Units":"°C",
	   "Description":"10 * Degrees ( °C ), -55 - +115, if 3000 – Dallas error",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toInt16"
	},
	"74":{
	   "No":"15",
	   "PropertyName":"Dallas Temperature 3",
	   "Bytes":"2",
	   "Type":"Signed",
	   "Min":"-55",
	   "Max":"3000",
	   "Multiplier":"10",
	   "Units":"°C",
	   "Description":"10 * Degrees ( °C ), -55 - +115, if 3000 – Dallas error",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toInt16"
	},
	"75":{
	   "No":"16",
	   "PropertyName":"Dallas Temperature Sensor ID1",
	   "Bytes":"8",
	   "Type":"Signed",
	   "Min":"0",
	   "Max":"-10000000000000000000",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"Temperature sensor ID",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"to[]byte"
	},
	"76":{
	   "No":"17",
	   "PropertyName":"Dallas Temperature Sensor ID2",
	   "Bytes":"8",
	   "Type":"Signed",
	   "Min":"0",
	   "Max":"-10000000000000000000",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"Temperature sensor ID",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"to[]byte"
	},
	"77":{
	   "No":"18",
	   "PropertyName":"Dallas Temperature Sensor ID3",
	   "Bytes":"8",
	   "Type":"Signed",
	   "Min":"0",
	   "Max":"-10000000000000000000",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"Temperature sensor ID",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"to[]byte"
	},
	"78":{
	   "No":"19",
	   "PropertyName":"iButton ID",
	   "Bytes":"8",
	   "Type":"Signed",
	   "Min":"0",
	   "Max":"-10000000000000000000",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"iButton ID number",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"to[]byte"
	},
	"79":{
	   "No":"20",
	   "PropertyName":"Network type",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"9",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"0 – 2G;2 – 3G;8 – LTE-M1;9 – NB-IOT.",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint8"
	},
	"80":{
	   "No":"21",
	   "PropertyName":"Working Mode",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"5",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"0 – home on stop,1 – home on move,2 – roaming on stop,3 – roaming on move,4 – unknown on stop,5 – unknown on move",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint8"
	},
	"99":{
	   "No":"22",
	   "PropertyName":"Continuous odometer",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"-",
	   "Units":"m",
	   "Description":"Continuous odometer value: m.",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint32"
	},
	"179":{
	   "No":"23",
	   "PropertyName":"Digital Output 1 state",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"Logic: 0 / 1",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint8"
	},
	"180":{
	   "No":"24",
	   "PropertyName":"Digital Output 2 state",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"Logic: 0 / 1",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint8"
	},
	"181":{
	   "No":"25",
	   "PropertyName":"PDOP",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"500",
	   "Multiplier":"0.1",
	   "Units":"-",
	   "Description":"Probability * 10; 0-500",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint16"
	},
	"182":{
	   "No":"26",
	   "PropertyName":"HDOP",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"500",
	   "Multiplier":"0.1",
	   "Units":"-",
	   "Description":"Probability * 10; 0-500",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint16"
	},
	"199":{
	   "No":"27",
	   "PropertyName":"Odometer Value (Virtual Odometer)",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"1",
	   "Units":"m",
	   "Description":"Distance between two records: m",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint32"
	},
	"200":{
	   "No":"28",
	   "PropertyName":"Deep Sleep",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"0 – not deep sleep mode,1 – deep sleep mode",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint8"
	},
	"205":{
	   "No":"29",
	   "PropertyName":"Cell ID",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"GSM base station ID",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint32"
	},
	"206":{
	   "No":"30",
	   "PropertyName":"Area Code",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65536",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"Location Area code (LAC), it depends on GSM operator. It provides unique number which assigned to a set of base GSM stations. Max value: 65536",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint16"
	},
	"239":{
	   "No":"31",
	   "PropertyName":"Ignition",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"0 – ignition off,1 – ignition on",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint8"
	},
	"240":{
	   "No":"32",
	   "PropertyName":"Movement Sensor",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"0 – not moving,1 – moving",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint8"
	},
	"241":{
	   "No":"33",
	   "PropertyName":"GSM Operator Code",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"-",
	   "Units":"-",
	   "Description":"Currently used GSM Operator code",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Permanent I/O elements",
	   "FinalConversion":"toUint32"
	},
	"81":{
	   "No":"34",
	   "PropertyName":"LVCAN Speed",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"1",
	   "Units":"km/h",
	   "Description":"Value in km/h",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"82":{
	   "No":"35",
	   "PropertyName":"LVCAN Accelerator Pedal Position",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"0.1",
	   "Units":"%",
	   "Description":"Value in %",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"83":{
	   "No":"36",
	   "PropertyName":"LVCAN Fuel Consumed",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"0.1",
	   "Units":"Ltr",
	   "Description":"Value in liters * 100",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"84":{
	   "No":"37",
	   "PropertyName":"LVCAN Fuel Level (liters)",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"0.1",
	   "Units":"Ltr",
	   "Description":"Value in liters * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"85":{
	   "No":"38",
	   "PropertyName":"LVCAN Engine RPM",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"Value in RPM",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"87":{
	   "No":"39",
	   "PropertyName":"LVCAN Total Mileage",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"1",
	   "Units":"m",
	   "Description":"Value in meters, m",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"89":{
	   "No":"40",
	   "PropertyName":"LVCAN Fuel Level (percentage)",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"0.1",
	   "Units":"%",
	   "Description":"Value in %",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"100":{
	   "No":"41",
	   "PropertyName":"LVCAN Program Number",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"999",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"Value: Min – 0, Max - 999",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"101":{
	   "No":"42",
	   "PropertyName":"LVCAN ModuleID",
	   "Bytes":"8",
	   "Type":"Signed",
	   "Min":"0",
	   "Max":"max",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"Module identification",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"to[]byte"
	},
	"102":{
	   "No":"43",
	   "PropertyName":"LVCAN Engine Work Time",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"1",
	   "Units":"Min",
	   "Description":"Value in min",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"103":{
	   "No":"44",
	   "PropertyName":"LVCAN Engine Work Time (counted)",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"1",
	   "Units":"Min",
	   "Description":"Value in min",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"104":{
	   "No":"45",
	   "PropertyName":"LVCAN Total Mileage",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"1",
	   "Units":"m",
	   "Description":"Value in meters, m",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"105":{
	   "No":"46",
	   "PropertyName":"LVCAN Total Mileage (counted)",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"1",
	   "Units":"m",
	   "Description":"Value in meters, m",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"106":{
	   "No":"47",
	   "PropertyName":"LVCAN Fuel Consumed",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"0.1",
	   "Units":"Ltr",
	   "Description":"Value in Ltr",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"107":{
	   "No":"48",
	   "PropertyName":"LVCAN Fuel Consumed (counted)",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"0.1",
	   "Units":"Ltr",
	   "Description":"Value in liters * 100",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"108":{
	   "No":"49",
	   "PropertyName":"LVCAN Fuel Level (percent)",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"0.1",
	   "Units":"%",
	   "Description":"Value in %",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"109":{
	   "No":"50",
	   "PropertyName":"LVCAN Fuel Level (liters)",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"0.1",
	   "Units":"Ltr",
	   "Description":"Value in Ltr",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"110":{
	   "No":"51",
	   "PropertyName":"LVCAN Fuel Rate",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"0.1",
	   "Units":"Ltr/h",
	   "Description":"Value in (liters * 10) / h",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"111":{
	   "No":"52",
	   "PropertyName":"LVCAN AdBlue Level (percent)",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"0.1",
	   "Units":"%",
	   "Description":"Value in %",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"112":{
	   "No":"53",
	   "PropertyName":"LVCAN AdBlue Level (liters)",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"0.1",
	   "Units":"Ltr",
	   "Description":"Value in liters * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"113":{
	   "No":"54",
	   "PropertyName":"LVCAN Engine RPM",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"Value in RPM",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"114":{
	   "No":"55",
	   "PropertyName":"LVCAN Engine Load",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"1",
	   "Units":"%",
	   "Description":"Value in %",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"115":{
	   "No":"56",
	   "PropertyName":"LVCAN Engine Temperature",
	   "Bytes":"2",
	   "Type":"Signed",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"0.1",
	   "Units":"°C",
	   "Description":"Value in °C x 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toInt16"
	},
	"116":{
	   "No":"57",
	   "PropertyName":"LVCAN Accelerator Pedal Position",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"0.1",
	   "Units":"%",
	   "Description":"Value in %",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"117":{
	   "No":"58",
	   "PropertyName":"LVCAN Vehicle Speed",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"1",
	   "Units":"km/h",
	   "Description":"Value in km/h",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"118":{
	   "No":"59",
	   "PropertyName":"LVCAN Axle 1 Load",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"kg",
	   "Description":"Value in kg",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"119":{
	   "No":"60",
	   "PropertyName":"LVCAN Axle 2 Load",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"kg",
	   "Description":"Value in kg",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"120":{
	   "No":"61",
	   "PropertyName":"LVCAN Axle 3 Load",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"kg",
	   "Description":"Value in kg",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"121":{
	   "No":"62",
	   "PropertyName":"LVCAN Axle 4 Load",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"kg",
	   "Description":"Value in kg",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"122":{
	   "No":"63",
	   "PropertyName":"LVCAN Axle 5 Load",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"kg",
	   "Description":"Value in kg",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"123":{
	   "No":"64",
	   "PropertyName":"LVCAN Control State Flags",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"see LVCAN IO element values",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"124":{
	   "No":"65",
	   "PropertyName":"LVCAN Agricultural Machinery Flags",
	   "Bytes":"8",
	   "Type":"Signed",
	   "Min":"0",
	   "Max":"max",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"see LVCAN IO element values",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"to[]byte"
	},
	"125":{
	   "No":"66",
	   "PropertyName":"LVCAN Harvesting Time",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"1",
	   "Units":"min",
	   "Description":"Vakue in min",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"126":{
	   "No":"67",
	   "PropertyName":"LVCAN Area of Harvest",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"1",
	   "Units":"m2",
	   "Description":"Value in m2",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"127":{
	   "No":"68",
	   "PropertyName":"LVCAN Mowing Efficiency",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"1",
	   "Units":"m2/h",
	   "Description":"Value in m2/h",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"128":{
	   "No":"69",
	   "PropertyName":"LVCAN Grain Mown Volume",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"1",
	   "Units":"kg",
	   "Description":"Value in kg",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"129":{
	   "No":"70",
	   "PropertyName":"LVCAN Grain Moisture",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"Value in %",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"130":{
	   "No":"71",
	   "PropertyName":"LVCAN Harvesting Drum RPM",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"-",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"131":{
	   "No":"72",
	   "PropertyName":"LVCAN Gap Under Harvesting Drum",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"1",
	   "Units":"mm",
	   "Description":"Value in mm",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"132":{
	   "No":"73",
	   "PropertyName":"LVCAN Security State Flags",
	   "Bytes":"8",
	   "Type":"Signed",
	   "Min":"0",
	   "Max":"max",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"see LVCAN IO element values",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"to[]byte"
	},
	"133":{
	   "No":"74",
	   "PropertyName":"LVCAN Tacho Total Vehicle Distance",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"1",
	   "Units":"m",
	   "Description":"Value in m",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"134":{
	   "No":"75",
	   "PropertyName":"LVCAN Trip Distance",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"1",
	   "Units":"m",
	   "Description":"Value in m",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"135":{
	   "No":"76",
	   "PropertyName":"LVCAN Tacho Vehicle Speed",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"km/h",
	   "Description":"Value in km/h",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"136":{
	   "No":"77",
	   "PropertyName":"LVCAN Tacho Driver Card Presence",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"see LVCAN IO element values",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"137":{
	   "No":"78",
	   "PropertyName":"LVCAN Driver1 States",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"see LVCAN IO element values",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"138":{
	   "No":"79",
	   "PropertyName":"LVCAN Driver2 States",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"see LVCAN IO element values",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"139":{
	   "No":"80",
	   "PropertyName":"LVCAN Driver1 Continuous Driving Time",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"min",
	   "Description":"Value in min",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"140":{
	   "No":"81",
	   "PropertyName":"LVCAN Driver2 Continuous Driving Time",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"min",
	   "Description":"Value in min",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"141":{
	   "No":"82",
	   "PropertyName":"LVCAN Driver1 Cumulative Break Time",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"min",
	   "Description":"Value in min",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"142":{
	   "No":"83",
	   "PropertyName":"LVCAN Driver2 Cumulative Break Time",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"min",
	   "Description":"Value in min",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"143":{
	   "No":"84",
	   "PropertyName":"LVCAN Driver1 Duration Of Selected Activity",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"min",
	   "Description":"Value in min",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"144":{
	   "No":"85",
	   "PropertyName":"LVCAN Driver2 Duration Of Selected Activity",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"min",
	   "Description":"Value in min",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"145":{
	   "No":"86",
	   "PropertyName":"LVCAN Driver1 Cumulative Driving Time",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"min",
	   "Description":"Value in min",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"146":{
	   "No":"87",
	   "PropertyName":"LVCAN Driver2 Cumulative Driving Time",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"min",
	   "Description":"Value in min",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"147":{
	   "No":"88",
	   "PropertyName":"LVCAN Driver1 ID High",
	   "Bytes":"8",
	   "Type":"Signed",
	   "Min":"0",
	   "Max":"max",
	   "Multiplier":"1",
	   "Units":"min",
	   "Description":"Driver1 ID High",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"to[]byte"
	},
	"148":{
	   "No":"89",
	   "PropertyName":"LVCAN Driver1 ID Low",
	   "Bytes":"8",
	   "Type":"Signed",
	   "Min":"0",
	   "Max":"max",
	   "Multiplier":"1",
	   "Units":"min",
	   "Description":"Driver1 ID Low",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"to[]byte"
	},
	"149":{
	   "No":"90",
	   "PropertyName":"LVCAN Driver2 ID High",
	   "Bytes":"8",
	   "Type":"Signed",
	   "Min":"0",
	   "Max":"max",
	   "Multiplier":"1",
	   "Units":"min",
	   "Description":"Driver2 ID High",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"to[]byte"
	},
	"150":{
	   "No":"91",
	   "PropertyName":"LVCAN Driver2 ID Low",
	   "Bytes":"8",
	   "Type":"Signed",
	   "Min":"0",
	   "Max":"max",
	   "Multiplier":"1",
	   "Units":"min",
	   "Description":"Driver2 ID Low",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"to[]byte"
	},
	"151":{
	   "No":"92",
	   "PropertyName":"LVCAN Battery Temperature",
	   "Bytes":"2",
	   "Type":"Signed",
	   "Min":"-255",
	   "Max":"65535",
	   "Multiplier":"0.1",
	   "Units":"°C",
	   "Description":"Value in °C x 10. Value is signed.",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toInt16"
	},
	"152":{
	   "No":"93",
	   "PropertyName":"LVCAN Battery Level (percent)",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"0.1",
	   "Units":"%",
	   "Description":"Value in percentages, %",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"90":{
	   "No":"94",
	   "PropertyName":"LVCAN Door Status",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"0 – all doors closed256 - front left door opened512 - front right door opened1024 - rear left door opened2048 - rear right door opened4096 - engine cover opened8192 - trunk door opened16128 - all doors opened",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"160":{
	   "No":"95",
	   "PropertyName":"LVCAN DTC Errors",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"DTC faults count",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"161":{
	   "No":"96",
	   "PropertyName":"LVCAN Slope of Arm",
	   "Bytes":"2",
	   "Type":"Signed",
	   "Min":"-65535",
	   "Max":"65535",
	   "Multiplier":"0.1",
	   "Units":"°",
	   "Description":"Value in °",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toInt16"
	},
	"162":{
	   "No":"97",
	   "PropertyName":"LVCAN Rotation of Arm",
	   "Bytes":"2",
	   "Type":"Signed",
	   "Min":"-65535",
	   "Max":"65535",
	   "Multiplier":"0.1",
	   "Units":"°",
	   "Description":"Value in °",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toInt16"
	},
	"163":{
	   "No":"98",
	   "PropertyName":"LVCAN Eject of Arm",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"0.1",
	   "Units":"m",
	   "Description":"Value in m * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"164":{
	   "No":"99",
	   "PropertyName":"LVCAN Horizontal Dist Arm Vechicle",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"0.1",
	   "Units":"m",
	   "Description":"Value in m * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"165":{
	   "No":"100",
	   "PropertyName":"LVCAN Height Arm Above Ground",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"0.1",
	   "Units":"m",
	   "Description":"Value in m * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"166":{
	   "No":"101",
	   "PropertyName":"LVC Drill RPM",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"-",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"167":{
	   "No":"102",
	   "PropertyName":"LVC Amount Of Spread Salt Square Meter",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"0.01",
	   "Units":"m",
	   "Description":"Value in g/m2",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"168":{
	   "No":"103",
	   "PropertyName":"LVC Battery Voltage",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"0.1",
	   "Units":"V",
	   "Description":"Value in V * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"169":{
	   "No":"104",
	   "PropertyName":"LVC Amount Spread Fine Grained Salt",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"0.1",
	   "Units":"t",
	   "Description":"Value in tons * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"170":{
	   "No":"105",
	   "PropertyName":"LVCAN Amount Spread Coarse Grained Salt",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"0.1",
	   "Units":"t",
	   "Description":"Value in tons * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"171":{
	   "No":"106",
	   "PropertyName":"LVCAN Amount Spread DiMix",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"0.1",
	   "Units":"t",
	   "Description":"Value in tons * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"172":{
	   "No":"107",
	   "PropertyName":"LVCAN Amount Spread Coarse Grained Calc",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"0.1",
	   "Units":"m3",
	   "Description":"Value in m3 * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"173":{
	   "No":"108",
	   "PropertyName":"LVCAN Amount Spread Calcium Chloride",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"0.1",
	   "Units":"m3",
	   "Description":"Value in m3 * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"174":{
	   "No":"109",
	   "PropertyName":"LVCAN Amount Spread Sodium Chloride",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"0.1",
	   "Units":"m3",
	   "Description":"Value in m3 * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"176":{
	   "No":"110",
	   "PropertyName":"LVCAN Amount Spread Magnesium Chloride",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"0.1",
	   "Units":"m3",
	   "Description":"Value in m3 * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"193":{
	   "No":"111",
	   "PropertyName":"LVCAN Amount Spread Gravel",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"0.1",
	   "Units":"t",
	   "Description":"Value in tons * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"178":{
	   "No":"112",
	   "PropertyName":"LVCAN Amount Spread Sand",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"0.1",
	   "Units":"t",
	   "Description":"Value in tons * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"183":{
	   "No":"113",
	   "PropertyName":"LVCAN Width Pouring Left",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"0.01",
	   "Units":"m",
	   "Description":"Value in m * 100",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"184":{
	   "No":"114",
	   "PropertyName":"LVCAN Width Pouring Right",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"0.01",
	   "Units":"m",
	   "Description":"Value in m * 100",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"185":{
	   "No":"115",
	   "PropertyName":"LVCAN Salt Spreader Work Hours",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"0.1",
	   "Units":"h",
	   "Description":"Value in h * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"186":{
	   "No":"116",
	   "PropertyName":"LVCAN Distance During Salting",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"0.1",
	   "Units":"km",
	   "Description":"Value in km * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"187":{
	   "No":"117",
	   "PropertyName":"LVCAN Load Weight",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"1",
	   "Units":"kg",
	   "Description":"Value in kg",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"188":{
	   "No":"118",
	   "PropertyName":"LVC Retarder Load",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"1",
	   "Units":"%",
	   "Description":"Valid range: 0 – 125%",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"189":{
	   "No":"119",
	   "PropertyName":"LVC Cruise Time",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"1",
	   "Units":"min",
	   "Description":"Value in min",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"190":{
	   "No":"120",
	   "PropertyName":"LVC CNG Status",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"255",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"0 – engine not on CNG1 – engine not on CNG",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint8"
	},
	"191":{
	   "No":"121",
	   "PropertyName":"LVC CNG Used",
	   "Bytes":"4",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"4294967295",
	   "Multiplier":"1",
	   "Units":"kg",
	   "Description":"Value in kg * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint32"
	},
	"192":{
	   "No":"122",
	   "PropertyName":"LVC CNG Level",
	   "Bytes":"2",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"65535",
	   "Multiplier":"1",
	   "Units":"%",
	   "Description":"Value in % * 10",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"ALLCAN300/LVCAN200 I/O elements",
	   "FinalConversion":"toUint16"
	},
	"155":{
	   "No":"123",
	   "PropertyName":"Geofence zone 01",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"Event:0 – target left zone,1 – target entered zone",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Eventual I/O elements",
	   "FinalConversion":"toUint8"
	},
	"156":{
	   "No":"124",
	   "PropertyName":"Geofence zone 02",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"Event:0 – target left zone,1 – target entered zone",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Eventual I/O elements",
	   "FinalConversion":"toUint8"
	},
	"157":{
	   "No":"125",
	   "PropertyName":"Geofence zone 03",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"Event:0 – target left zone,1 – target entered zone",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Eventual I/O elements",
	   "FinalConversion":"toUint8"
	},
	"158":{
	   "No":"126",
	   "PropertyName":"Geofence zone 04",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"Event:0 – target left zone,1 – target entered zone",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Eventual I/O elements",
	   "FinalConversion":"toUint8"
	},
	"159":{
	   "No":"127",
	   "PropertyName":"Geofence zone 05",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"Event:0 – target left zone,1 – target entered zone",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Eventual I/O elements",
	   "FinalConversion":"toUint8"
	},
	"175":{
	   "No":"128",
	   "PropertyName":"Auto Geofence",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"Event:0 – target left zone,1 – target entered zone",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Eventual I/O elements",
	   "FinalConversion":"toUint8"
	},
	"177":{
	   "No":"129",
	   "PropertyName":"Idling",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"1 – idling start,0 – idling stop",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Eventual I/O elements",
	   "FinalConversion":"toUint8"
	},
	"249":{
	   "No":"130",
	   "PropertyName":"Jamming detection",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"0 – not jammed,1 – jammed",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Eventual I/O elements",
	   "FinalConversion":"toUint8"
	},
	"250":{
	   "No":"131",
	   "PropertyName":"Trip",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"1 – trip start,0 – trip stop",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Eventual I/O elements",
	   "FinalConversion":"toUint8"
	},
	"251":{
	   "No":"132",
	   "PropertyName":"Immobilizer",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"1 – iButton connected",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Eventual I/O elements",
	   "FinalConversion":"toUint8"
	},
	"252":{
	   "No":"133",
	   "PropertyName":"Authorized driving",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"1",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"1 – authorized iButton connected",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Eventual I/O elements",
	   "FinalConversion":"toUint8"
	},
	"253":{
	   "No":"134",
	   "PropertyName":"Green driving type",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"10",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"1 – harsh acceleration,2 – harsh braking,3 - harsh cornering",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Eventual I/O elements",
	   "FinalConversion":"toUint8"
	},
	"254":{
	   "No":"135",
	   "PropertyName":"Green driving value",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"10000",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"Depending on green driving type: if harsh acceleration or braking – g*100 (value 123 -> 1.23g), if harsh cornering – degrees (value in radians)",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Eventual I/O elements",
	   "FinalConversion":"toUint8"
	},
	"255":{
	   "No":"136",
	   "PropertyName":"Over Speeding",
	   "Bytes":"1",
	   "Type":"Unsigned",
	   "Min":"0",
	   "Max":"400",
	   "Multiplier":"1",
	   "Units":"-",
	   "Description":"At over speeding start km/h, at over speeding end km/h",
	   "HWSupport":"FM3612, FM36M1",
	   "Parametr Group":"Eventual I/O elements",
	   "FinalConversion":"toUint8"
	}
 }`
